name: .NET Desktop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest

    env:
      # Replace with your actual solution file name.
      Solution_Name: NormalSmith.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies using MSBuild
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}
        shell: pwsh

      - name: Build the solution using MSBuild
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:OutDir="$env:GITHUB_WORKSPACE\build\"
        shell: pwsh
      

      - name: Sign the Executable (Release only)
        if: ${{ matrix.configuration == 'Release' }}
        shell: pwsh
        run: |
          Write-Host "Decoding the signing certificate..."
          $pfxBytes = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}")
          $certPath = "$env:GITHUB_WORKSPACE\signingCertificate.pfx"
          [System.IO.File]::WriteAllBytes($certPath, $pfxBytes)
          
          Write-Host "Locating the executable..."
          $exePath = "$env:GITHUB_WORKSPACE\NormalSmith\bin\Release\NormalSmith.exe"
          if (-Not (Test-Path $exePath)) {
            Write-Error "Executable not found at path: $exePath"
            exit 1
          }
          
          Write-Host "Signing the executable..."
          signtool sign /f $certPath /p "${{ secrets.PFX_KEY }}" /tr http://timestamp.digicert.com /td sha256 /fd sha256 $exePath
          
          Write-Host "Cleaning up certificate file..."
          Remove-Item -Path $certPath
